export enum TypologyCategory {
  STRUCTURING = 'STRUCTURING',
  SMURFING = 'SMURFING',
  LAYERING = 'LAYERING',
  PLACEMENT = 'PLACEMENT',
  INTEGRATION = 'INTEGRATION',
  PEP = 'PEP',
  FRAUD_ML = 'FRAUD_ML',
  GEO_RISK = 'GEO_RISK',
  TBML = 'TBML',
  MULE_ACTIVITY = 'MULE_ACTIVITY',
  VELOCITY = 'VELOCITY'
}
